version: "3.3"
services:
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_USER=empdbuser
      - MYSQL_PASSWORD=empdbuserpassword
      - MYSQL_ROOT_PASSWORD=empdbrootpassword
      - MYSQL_DATABASE=empdb    
    volumes:
      - db-vol:/var/lib/mysql
    restart: always
  backend:
    image: andyvan27/emp-app-backend:v1.0.0
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_NAME=empdb
      - DB_USER=empdbuser
      - DB_PASSWORD=empdbuserpassword
    ports:
      - "80:8080"
    restart: always    

volumes:
  db-vol: